services:
  sonosd:
    build:
      context: .
      args:
        VERSION: ${VERSION:-1.0.0}
        PORT: ${PORT:-5005}
    image: sonos-alexa-api:latest
    container_name: sonosd
    network_mode: host
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-5005}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_FORMAT=${LOG_FORMAT:-}
      - DEBUG_LEVEL=${DEBUG_LEVEL:-}
      - DEBUG_CATEGORIES=${DEBUG_CATEGORIES:-}
    volumes:
      - ./settings.json:/app/settings.json:ro
      # Mount external presets if HOST_PRESET_PATH is set in .env
      - ${HOST_PRESET_PATH:-./presets}:/app/presets:ro
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
        compress: "true"
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:' + process.env.PORT + '/health').then(r => process.exit(r.ok ? 0 : 1)).catch(() => process.exit(1))"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s