version: '3.8'

services:
  sonos-api:
    build: .
    image: sonos-alexa-api:latest
    container_name: sonos-alexa-api
    network_mode: host
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - PORT=5005
    volumes:
      - ./config.json:/app/config.json:ro
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:5005/health').then(r => process.exit(r.ok ? 0 : 1)).catch(() => process.exit(1))"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s