parameters:
  room:
    name: room
    in: path
    required: true
    description: Room name (case-insensitive, URL-encode if contains spaces)
    schema:
      type: string
      example: Kitchen
      
  preset:
    name: preset
    in: path
    required: true
    description: Preset name
    schema:
      type: string
      example: morning-jazz
      
  level:
    name: level
    in: path
    required: true
    description: Volume level (0-100)
    schema:
      type: integer
      minimum: 0
      maximum: 100
      example: 50
      
  delta:
    name: delta
    in: path
    required: true
    description: Volume change amount
    schema:
      type: integer
      minimum: 1
      maximum: 100
      example: 10
      
  toggle:
    name: toggle
    in: path
    required: true
    description: Toggle state
    schema:
      type: string
      enum: [on, off]
      example: on
      
  text:
    name: text
    in: path
    required: true
    description: Text to announce
    schema:
      type: string
      example: Dinner is ready
      
  volume:
    name: volume
    in: path
    required: true
    description: Announcement volume
    schema:
      type: integer
      minimum: 0
      maximum: 100
      example: 40
      
  service:
    name: service
    in: path
    required: true
    description: Music service
    schema:
      type: string
      enum: [apple, library, pandora]
      example: apple
      
  query:
    name: query
    in: path
    required: true
    description: Search query
    schema:
      type: string
      example: Yesterday Beatles
      
  name:
    name: name
    in: path
    required: true
    description: Item name
    schema:
      type: string
      example: My Favorite