get:
  tags:
    - System
  summary: Get current settings
  description: Returns the current API settings from settings.json
  operationId: getSettings
  responses:
    '200':
      description: Current settings
      content:
        application/json:
          schema:
            type: object
            properties:
              host:
                type: string
                example: 192.168.1.100
              port:
                type: integer
                example: 5005
              defaultRoom:
                type: string
                example: Living Room
              announceVolume:
                type: integer
                example: 40
              auth:
                type: object
                properties:
                  username:
                    type: string
                    example: user
                  rejectUnauthorized:
                    type: boolean
                    example: true
              voicerss:
                type: string
                description: API key present (masked)
                example: ****
              macSay:
                type: object
                properties:
                  voice:
                    type: string
                    example: Alex
                  rate:
                    type: integer
                    example: 175
              pandora:
                type: object
                properties:
                  username:
                    type: string
                    example: user@example.com